"""Compliance verification node module for LangGraph orchestration.

This module evaluates proposals generated by the portfolio agent against 
SEBI/RBI regulations stored in a Qdrant vector database, enforcing strict 
regulatory constraints and providing citation-backed explanations.
"""

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import AIMessage
from langchain_groq import ChatGroq
from pydantic import BaseModel, Field
from qdrant_client import QdrantClient
from typing import List
import sys
import os

sys.path.append(os.path.join(os.path.dirname(__file__), '../../'))
from shared.security_config import get_groq_api_key
from langgraph_orchestrator.state import AgentState

llm = ChatGroq(
    model=os.getenv("GROQ_REASONING_MODEL", "llama-3.3-70b-versatile"),
    api_key=get_groq_api_key(),
    temperature=0,
)

qdrant_url = os.getenv("QDRANT_URL")
qdrant_key = os.getenv("QDRANT_API_KEY")

try:
    client = QdrantClient(url=qdrant_url, api_key=qdrant_key)
    client.set_model("BAAI/bge-small-en-v1.5")
except Exception as e:
    print(f"Warning: Failed to initialize QdrantClient in compliance_node: {e}")
    client = None


class ComplianceEval(BaseModel):
    """Schema defining the structured compliance evaluation output.
    
    Attributes:
        is_compliant: Boolean indicating if the proposal adheres to the retrieved rules.
        explanation: Detailed reasoning for the compliance verdict.
        citations: List of regulatory sources backing the decision.
    """
    is_compliant: bool = Field(..., description="Whether the proposal is compliant with the retrieved rules.")
    explanation: str = Field(..., description="A detailed explanation of why the proposal is or is not compliant.")
    citations: List[str] = Field(..., description="A list of strict document sources/citations used from the Qdrant DB to form this conclusion (e.g., ['SEBI_101', 'RBI_MRMF_42']).")


system_prompt = """You are the Chief Compliance Officer for Pramiti OS.
Your role is to mathematically evaluate the Relationship Manager's proposal against the provided regulatory rules from Qdrant.

PROPOSAL:
{proposal}

RETRIEVED REGULATORY RULES:
{rules}

You MUST evaluate the proposal. If it violates any rule (e.g., allocating >30% equity for a conservative profile, or liquidating > ₹5Cr without Tier 2 approval), you must flag it as non-compliant.
You MUST output your evaluation in structured JSON matching the requested schema. You MUST include citations referencing the 'source' metadata of the rules you used.
"""

def compliance_node(state: AgentState) -> dict:
    """Evaluates the generated portfolio proposal against regulatory rules.
    
    Interfaces with the Qdrant vector database to retrieve relevant SEBI/RBI 
    regulations based on the proposal text. Utilizes an LLM to form a 
    structured compliance verdict with strict citations.
    
    Args:
        state: The current state of the LangGraph workflow.
        
    Returns:
        dict: A dictionary containing the updated `messages` list, appending 
              the compliance evaluation payload to the latest proposal.
    """
    messages = state.get("messages", [])
    
    raw_content = messages[-1].content
    proposal_str = (
        raw_content if isinstance(raw_content, str)
        else " ".join(str(part) for part in raw_content)
    )

    if not client:
        return {
            "messages": [AIMessage(content="⚠️ Compliance Node Error: Could not connect to Qdrant. Proposal cannot be verified.")]
        }

    try:
        search_result = client.query(
            collection_name="compliance_rules",
            query_text=proposal_str,
            limit=3
        )
        
        rules_text = ""
        for i, res in enumerate(search_result):
            source = res.metadata.get("source", f"Doc_{i}")
            rules_text += f"[Citation: {source}] {res.document}\n"
            
    except Exception as e:
        return {
            "messages": [AIMessage(content=f"⚠️ Compliance Node Error: Failed to retrieve rules from Qdrant. {str(e)}")]
        }

    evaluator_llm = llm.with_structured_output(ComplianceEval)
    
    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt)
    ])
    
    chain = prompt | evaluator_llm
    
    raw_eval = chain.invoke({
        "proposal": proposal_str,
        "rules": rules_text
    })
    
    if isinstance(raw_eval, dict):
        evaluation = ComplianceEval.model_validate(raw_eval)
    elif isinstance(raw_eval, ComplianceEval):
        evaluation = raw_eval
    else:
        evaluation = ComplianceEval.model_validate(raw_eval.model_dump() if hasattr(raw_eval, "model_dump") else raw_eval)
    
    payload = {
        "is_compliant": evaluation.is_compliant,
        "explanation": evaluation.explanation,
        "citations": evaluation.citations
    }
    
    import json
    report_text = f"\n\n<compliance_verdict>\n{json.dumps(payload)}\n</compliance_verdict>\n\n"

    new_proposal_text = proposal_str + "\n" + report_text
    new_messages = messages.copy()
    new_messages[-1] = AIMessage(content=new_proposal_text)

    return {
        "messages": new_messages
    }
